### PR TITLE
feat(prettier): add pluginSearchDirs type definition

### PR DESCRIPTION
**Pull request by kunish**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test prettier`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/prettier/prettier/blob/main/src/main/core-options.js#L172
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by kunish** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55962

**Comment by Shinigami92** [comment]
This you need to make a rebase or so?

**Comment by kunish** [comment]
@Shinigami92 A rebase I guess? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55962#issuecomment-926366918

**Comment by kunish** [comment]
Never done that and having no idea tbh. Maybe you can give some hint. I'll be happy to make that change.

**Comment by Shinigami92** [comment]
I think it will be something like

within your branch `prettier-plugin-search-dirs`

```
gh pr checkout 55873 # get the other PR
git switch prettier-plugin-search-dirs # switch back to your branch
git rebase -i prettier-2.4-types # rebase interactive
```

If this doesn't work, I think you could still just reopen a new PR or request your changes in the other PR :shrug: 
This or that way, it's just important to get the changes somehow :sweat_smile:

**Comment by kunish** [comment]
Thanks 😊, I'm definitely gonna try these out.

**Pull request closed without merging**
